### PR TITLE
Support for stateless refresh token and new openapi definition.

### PR DESCRIPTION
**Pull request by danforero**
### Problem

There is no way to refresh the token when this is read from a database (offline.access)  there is a way to set the stored token in the client but the refresh token function does not send the code verification parameter.

### Solution

I added two optional parameters to the OAuth2User constructor, also code_verifier is added as a class property.

generateUrlOptions: its type is GenerateAuthUrlOptions, if used it generates code_verifier.
token: its type is Token, it can be used with a token read from a database.

Token type is exported to be used outside of the client.

This PR also includes a test for this feature /examples/oauth2-offline_pkce_s256.ts, this example uses ../dist instead of the npm twitter library because this feature is not included yet in npm

### Result

You will be able to create a client using a stored token for offline access.

### CODE REVIEW

**Review by kochie — APPROVED** [review]

**Comment by Monneraldo** [comment]
My friend's twitter account @chinanws22 was wrongfully suspended as he is
not a bot, neither was he spamming. Please reinstate his account

في الأحد، ١٨ ديسمبر ٢٠٢٢ ٣:٠٩ م Robert Koch ***@***.***> كتب:

**Comment by kochie** [comment]
@danforero I opened your PR in my fork https://github.com/kochie/twitter-api-typescript-sdk/pull/1

**Comment by Monneraldo** [comment]
My friend's twitter account @chinanws22 was wrongfully suspended as he is
not a bot, neither was he spamming. Please reinstate his account

في الاثنين، ١٩ ديسمبر ٢٠٢٢ ٦:٥٨ ص Robert Koch ***@***.***>
كتب:

**Comment by Monneraldo** [comment]
My only dream in 2022 was to get my suspended account back before 2023, but
it hasn't come true yet

في الاثنين، ١٩ ديسمبر ٢٠٢٢ ٧:٠١ ص منير الدبعي ***@***.***> كتب:

**Comment by Monneraldo** [comment]
I suffer from epilepsy. Please help me recover my account. If you do not
have the authority to recover the account, please send this message to
someone who can help me recover the account. I do not want to go to the
hospital because of my loss of the account. There is a chronic headache due
to illness and thinking about the account. Please help me. I will pray to
you.

@Chinanws22



في الاثنين، ٢ يناير ٢٠٢٣ ٢:١٧ ص منير الدبعي ***@***.***> كتب:

**Comment by maied12** [comment]
> ### Problem
> 
> There is no way to refresh the token when this is read from a database (offline.access)  there is a way to set the stored token in the client but the refresh token function does not send the code verification parameter.
> 
> ### Solution
> 
> I added two optional parameters to the OAuth2User constructor, also code_verifier is added as a class property.
> 
> generateUrlOptions: its type is GenerateAuthUrlOptions, if used it generates code_verifier.
> token: its type is Token, it can be used with a token read from a database.
> 
> Token type is exported to be used outside of the client.
> 
> This PR also includes a test for this feature /examples/oauth2-offline_pkce_s256.ts, this example uses ../dist instead of the npm twitter library because this feature is not included yet in npm
> 
> 
> ### Result
> 
> You will be able to create a client using a stored token for offline access.
>

**Comment by Monneraldo** [comment]
I suffer from epilepsy. Please help me recover my account. If you do not
have the authority to recover the account, please send this message to
someone who can help me recover the account. I do not want to go to the
hospital because of my loss of the account. There is a chronic headache due
to illness and thinking about the account. Please help me. I will pray to
you

I suffer from epilepsy. Please help me recover my account. If you do not
have the authority to recover the account, please send this message to
someone who can help me recover the account. I do not want to go to the
hospital because of my loss of the account. There is a chronic headache due
to illness and thinking about the account. Please help me. I will pray to
you

في الأحد، ٢٩ يناير ٢٠٢٣ ٣:٤٢ ص مسريها ***@***.***> كتب:

**Comment by danforero** [comment]
Twitter API v2 seems to have several problems with Tokens expiring before time, it's being almost a year and the problem is still there:

https://twittercommunity.com/t/refresh-token-expiring-with-offline-access-scope/168899

It looks like twitter API v2 development is abandoned, I'm, closing this PR.

**Pull request closed without merging**
